-- Migration: Add Indexes for Unindexed Foreign Keys
-- Generated by Dev Refactor v4 (Phase 1.4.1)
-- Date: 2026-01-10
-- Purpose: Improve FK query performance based on Supabase Advisors

-- Index for media.created_by (FK: media_created_by_fkey)
-- Advisors warning: "Table `public.media` has a foreign key `media_created_by_fkey` without a covering index"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_media_created_by
ON public.media(created_by);

-- Index for project_media.media_id (FK: project_media_media_id_fkey)
-- Advisors warning: "Table `public.project_media` has a foreign key `project_media_media_id_fkey` without a covering index"
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_project_media_media
ON public.project_media(media_id);

-- Note: These indexes will improve JOIN performance when querying via FK columns
-- Verify with: EXPLAIN ANALYZE SELECT * FROM media JOIN profiles ON media.created_by = profiles.id;
